stages:
  - setup
  - build
  - test

# cache:
#   paths:
#     - .pip-cache/
#     - venv/

setup-python:
  stage: setup
  tags:
    - main
  variables:
   PYTHON_VERSION: "3.13.0"
  script:
    - echo "Setting up Python ..."

    # - Set-ExecutionPolicy Bypass -Scope Process -Force

    # - if (-not (Test-Path "$env:ProgramData\chocolatey\choco.exe")) {
    #     [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
    #   iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    #   }
    - Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - choco install python --version=$env:PYTHON_VERSION -y --no-progress
    
    - $env:Path = "C:\Python${env:PYTHON_VERSION};C:\Python${env:PYTHON_VERSION}\Scripts;" + $env:Path
    
    - python --version
    
    - pip --version
    
    - echo "Hooray, Python's done setting up!"

setup-venv:
  stage: setup
  tags:
    - main
  script:
    - echo "Setting up venv..."

    - pip install -r requirements.txt

    - .\scripts\activate-venv.ps1

    - .\scripts\check-django.ps1

    - .\scripts\format.ps1

    - .\scripts\setup.ps1

    - pre-commit install

    - echo "Finish setting up venv..."
  dependencies:
    - setup-python
  # artifacts:
  #   paths:
  #     - venv/

build-job:
  stage: build
  tags:
    - main
  script:
    - echo "Building..."

    - .\scripts\activate-venv.ps1

    - python manage.py check

    - python manage.py migrate --noinput

    - python manage.py collectstatic --noinput

    - echo "Done building..."
  dependencies:
    - setup-python
    - setup-venv

test-job:
  stage: test
  tags:
    - main
  script:
    - echo "Begin testing..."

    - .\scripts\activate-venv.ps1

    - black --check .

    - flake8 .

    - pre-commit run --all-files

    - coverage run --source='.' manage.py test

    - coverage report

    - bandit -r .

    - python manage.py makemigrations --check --dry-run

    - echo "☝️🤓 TEST FINISH ✅!"
  dependencies:
    - setup-python
    - setup-venv