# Define pipeline stages (executed in order)
stages:
  - build
  - test

# First job: Build stage
build-job:
  stage: build
  script:
    - ./scripts/activate-venv.ps1
    - ./scripts/check-django.ps1
    - ./scripts/format.ps1
    - ./scripts/setup.ps1
    - echo "Compiling the code..."
    - echo "Building the project..."

# Second job: Test stage
test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - echo "Running lint checks..."