stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "onion and garlic"
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - ./scripts/activate-venv.ps1
    - ./scripts/check-django.ps1
    - ./scripts/format.ps1
    - ./scripts/setup.ps1
    - echo "Compiling the code..."
    - echo "Building the project..."

test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - echo "Running lint checks..."