stages:
  - setup
  - build
  - test

# cache:
#   paths:
#     - .pip-cache/
#     - venv/

setup-venv:
  stage: setup
  tags:
    - main
  script:
    - echo "Setting up venv..."
    - pip install -r requirements.txt
    - .\scripts\activate-venv.ps1
    - .\scripts\check-django.ps1
    - .\scripts\format.ps1
    - .\scripts\setup.ps1
    # - .\Scripts\python.exe -m pip install --upgrade pip
    - pre-commit install
    - echo "Finish setting up venv..."
  # artifacts:
  #   paths:
  #     - venv/

build-job:
  stage: build
  tags:
    - main
  script:
    - echo "Building..."
    - .\scripts\activate-venv.ps1
    - python manage.py check
    - python manage.py migrate --noinput
    - python manage.py collectstatic --noinput
    - echo "Done building..."
  dependencies:
    - setup-venv

test-job:
  stage: test
  tags:
    - main
  script:
    - echo "Begin testing..."
    - .\scripts\activate-venv.ps1
    - black --check .
    - flake8 .
    - pre-commit run --all-files
    - coverage run --source='.' manage.py test
    - coverage report
    - bandit -r .
    - python manage.py makemigrations --check --dry-run
    - echo "☝️🤓 TEST FINISH ✅!"
  dependencies:
    - setup-venv