stages:
  - build
  - test

build-job:
  # tags:
  #   - windows
  #   - shell
  stage: build
  script:
    - echo "onion and garlic"
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "Compiling the code..."
    - echo "Building the project..."

test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - echo "Running lint checks..."