stages:
  - setup
  - build
  - test

# cache:
#   paths:
#     - .pip-cache/
#     - venv/

setup-python:
  stage: setup
  tags:
    - main
  variables:
   PYTHON_VERSION: "3.13.0"
  script:
    - echo "Setting up Python ..."
    - Invoke-WebRequest -Uri "https://www.python.org/ftp/python/${env:PYTHON_VERSION}/python-${env:PYTHON_VERSION}-amd64.exe" -OutFile "python-installer.exe"
    - Start-Process "python-installer.exe" -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1" -Wait
    - Remove-Item -Force "python-installer.exe" # Clean up the installer file
  # Verify installations
    - python --version
    - pip --version
    - python -m pip install --upgrade pip
    - echo "Python setup complete!"


setup-venv:
  stage: setup
  tags:
    - main
  script:
    - echo "Setting up venv..."

    - pip install -r requirements.txt

    - .\scripts\activate-venv.ps1

    - .\scripts\check-django.ps1

    - .\scripts\format.ps1

    - .\scripts\setup.ps1

    - pre-commit install

    - echo "Finish setting up venv..."
  dependencies:
    - setup-python
  # artifacts:
  #   paths:
  #     - venv/

build-job:
  stage: build
  tags:
    - main
  script:
    - echo "Building..."

    - .\scripts\activate-venv.ps1

    - python manage.py check

    - python manage.py migrate --noinput

    - python manage.py collectstatic --noinput

    - echo "Done building..."
  dependencies:
    - setup-python
    - setup-venv

test-job:
  stage: test
  tags:
    - main
  script:
    - echo "Begin testing..."

    - .\scripts\activate-venv.ps1

    - black --check .

    - flake8 .

    - pre-commit run --all-files

    - coverage run --source='.' manage.py test

    - coverage report

    - bandit -r .

    - python manage.py makemigrations --check --dry-run

    - echo "☝️🤓 TEST FINISH ✅!"
  dependencies:
    - setup-python
    - setup-venv