version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn Off_Axis_Django.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - static_volume:/app/static
      - type: bind
        source: ./db.sqlite3
        target: /app/db.sqlite3
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
