# Generated by Django 5.1.2 on 2024-12-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_1", models.TextField(max_length=256)),
                ("line_2", models.TextField(max_length=256)),
                ("country", models.TextField(max_length=256)),
                ("city", models.TextField(max_length=256)),
                ("state_or_province", models.TextField(max_length=256)),
                ("post_code", models.TextField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name="artist",
            name="gigs",
        ),
        migrations.CreateModel(
            name="Gig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=19)),
                (
                    "booking_fee",
                    models.DecimalField(decimal_places=2, default=1.25, max_digits=19),
                ),
                ("capacity", models.IntegerField()),
                ("description", models.TextField(max_length=500)),
                ("gig_photo_url", models.TextField(max_length=2048)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Off_Axis_App.artist",
                    ),
                ),
                (
                    "supporting_artists",
                    models.ManyToManyField(
                        blank=True,
                        related_name="supporting_artists",
                        to="Off_Axis_App.artist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount_used", models.TextField(blank=True, max_length=256)),
                ("is_used", models.BooleanField(default=False)),
                (
                    "gig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Off_Axis_App.gig",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Off_Axis_App.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=500)),
                ("description", models.TextField(max_length=500)),
                ("venue_photo_url", models.TextField(max_length=2048)),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Off_Axis_App.address",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gig",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Off_Axis_App.venue"
            ),
        ),
    ]
