# Generated by Django 5.1.2 on 2025-02-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="artists/"),
        ),
    ]
