# Generated by Django 5.1.2 on 2024-11-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0002_address_remove_artist_gigs_gig_ticket_venue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="bookingFee",
            field=models.DecimalField(decimal_places=2, default=1.25, max_digits=19),
        ),
    ]
