# Generated by Django 5.1.2 on 2025-03-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0002_credit_artist_credit_credittransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
