# Generated by Django 5.1.2 on 2025-03-12 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0002_credit_artist_credit_credittransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="CMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artist_of_the_week",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Off_Axis_App.artist",
                    ),
                ),
                (
                    "featured_gigs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="featured_in_cms",
                        to="Off_Axis_App.gig",
                    ),
                ),
                (
                    "just_announced_gigs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="just_announced_in_cms",
                        to="Off_Axis_App.gig",
                    ),
                ),
            ],
        ),
    ]
