# Generated by Django 5.1.2 on 2024-11-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0003_gig_bookingfee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gig",
            old_name="bookingFee",
            new_name="booking_fee",
        ),
    ]
