# Generated by Django 5.1.2 on 2025-02-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0002_alter_artist_profile_picture"),
        ("Off_Axis_App", "0003_alter_sociallink_type"),
    ]

    operations = []
