# Generated by Django 5.1.2 on 2025-03-19 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0003_gig_is_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
