# Generated by Django 5.1.2 on 2025-03-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0003_cms"),
        ("Off_Axis_App", "0004_ticket_created_at"),
    ]

    operations = []
