# Generated by Django 5.1.2 on 2025-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0005_merge_0003_cms_0004_ticket_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gig",
            name="gig_photo_url",
        ),
        migrations.AddField(
            model_name="gig",
            name="gig_picture",
            field=models.ImageField(blank=True, null=True, upload_to="gigs/"),
        ),
    ]
