# Generated by Django 5.1.2 on 2024-12-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0005_contactinformation_festival"),
    ]

    operations = [
        migrations.AddField(
            model_name="festival",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="slug",
            field=models.SlugField(default="default-slug", unique=True),
        ),
    ]
