# Generated by Django 5.1.2 on 2024-12-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0006_festival_is_active_festival_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="festival",
            name="festival_photo_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="festival",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
