# Generated by Django 5.1.2 on 2025-03-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0006_remove_gig_gig_photo_url_gig_gig_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="venue_photo_url",
        ),
        migrations.AddField(
            model_name="venue",
            name="venue_picture",
            field=models.ImageField(blank=True, null=True, upload_to="venues/"),
        ),
    ]
