# Generated by Django 5.1.2 on 2024-11-27 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0006_cartitem_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="cart",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Off_Axis_App.cart",
            ),
        ),
    ]
