# Generated by Django 5.1.2 on 2024-12-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0007_artist_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
