# Generated by Django 5.1.2 on 2024-12-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0009_gig_stripe_product_id_alter_gig_supporting_artists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gig",
            name="supporting_artists",
            field=models.ManyToManyField(
                blank=True, related_name="supporting_artists", to="Off_Axis_App.artist"
            ),
        ),
    ]
