# Generated by Django 5.1.2 on 2025-01-21 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0012_remove_artist_profile_picture_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="checkout_email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Off_Axis_App.client",
            ),
        ),
    ]
