# Generated by Django 5.1.2 on 2025-01-21 23:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0013_ticket_checkout_email_alter_ticket_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="qr_code",
            field=models.ImageField(blank=True, upload_to="ticket-qr-codes/"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="qr_code_data",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
