# Generated by Django 5.1.2 on 2025-02-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0013_spotifytoken"),
        ("Off_Axis_App", "0014_ticket_qr_code_ticket_qr_code_data"),
    ]

    operations = []
