# Generated by Django 5.1.2 on 2025-02-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0015_merge_20250212_1426"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="checkout_country",
            field=models.TextField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="checkout_name",
            field=models.TextField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="checkout_postcode",
            field=models.TextField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
