# Generated by Django 5.1.2 on 2025-02-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0015_alter_sociallink_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="type",
            field=models.CharField(
                choices=[
                    ("Spotify", "Spotify"),
                    ("YouTube", "YouTube"),
                    ("SoundCloud", "SoundCloud"),
                    ("Instagram", "Instagram"),
                    ("WhatsApp", "WhatsApp"),
                ],
                max_length=100,
            ),
        ),
    ]
