# Generated by Django 5.1.2 on 2025-02-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0015_credit_artist_credit_credittransaction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="credit",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="transaction",
        ),
    ]
