# Generated by Django 5.1.2 on 2025-02-19 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0016_remove_artist_credit_remove_artist_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="credit",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist_credit",
                to="Off_Axis_App.credit",
            ),
        ),
    ]
