# Generated by Django 5.1.2 on 2025-02-19 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0017_artist_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Off_Axis_App.credittransaction",
            ),
        ),
    ]
