# Generated by Django 5.1.2 on 2025-02-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0018_artist_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="balance",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="credittransaction",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
