# Generated by Django 5.1.2 on 2025-02-25 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0019_alter_credit_balance_alter_credittransaction_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credittransaction",
            name="from_artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sent_transactions",
                to="Off_Axis_App.artist",
            ),
        ),
    ]
