# Generated by Django 5.1.2 on 2025-02-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0020_alter_credittransaction_from_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credittransaction",
            name="from_artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_transactions",
                to="Off_Axis_App.artist",
            ),
        ),
        migrations.AlterField(
            model_name="credittransaction",
            name="to_artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_transactions",
                to="Off_Axis_App.artist",
            ),
        ),
    ]
