# Generated by Django 5.1.2 on 2025-02-26 00:00

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Off_Axis_App", "0022_remove_artist_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="credittransaction",
            name="gig",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.expressions.Case,
                to="Off_Axis_App.gig",
            ),
        ),
        migrations.AlterField(
            model_name="credittransaction",
            name="from_artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_transactions",
                to="Off_Axis_App.artist",
            ),
        ),
        migrations.AlterField(
            model_name="credittransaction",
            name="to_artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_transactions",
                to="Off_Axis_App.artist",
            ),
        ),
    ]
